name: web_portfolio
description: Flutter Web Portfolio Landing Page.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  responsive_framework: ^0.0.14
  flutter_icons: ^1.1.0
  smooth_page_indicator: ^0.2.0
  carousel_slider: ^3.0.0
  fancy_cursor: ^0.1.2
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Peyda
      fonts:
        - asset: assets/fonts/Peyda-Black.ttf
          weight: 900
        - asset: assets/fonts/Peyda-Bold.ttf
          weight: 700
        - asset: assets/fonts/Peyda-Medium.ttf
          weight: 500
        - asset: assets/fonts/Peyda-Regular.ttf
          weight: 400
        - asset: assets/fonts/Peyda-Light.ttf
          weight: 300
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300